name: Continuous Delivery

on:
  push:
    branches:
      - main
    paths:
      - "src/**"

env:
  DOCKER_IMAGE: "datadrivet-template" # change this to reflect the project name
  DOCKERFILE: "./Dockerfile"
  SOURCE_PATH: "."

jobs:
  # Check if product critical files have been modified
  check_source_file_change:
    name: "Check source file changes"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    outputs:
      file_changes: ${{ steps.filter.outputs.source }}
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          sparse-checkout: ${{ env.SOURCE_PATH }}
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: shell
          filters: |
            source:
              - './src/**/*.py'
              - './Dockerfile'

  bump_version:
    name: "Bump version"
    runs-on: ubuntu-latest
    needs: check_source_file_change
    # If statement that will run the job only when:
    # - the commit message does not start with 'bump:'
    # - source files have been modified i.e. files in folders used by Dockerfile
    if: ${{ !startsWith(github.event.head_commit.message, 'bump:') && needs.check_source_file_change.outputs.file_changes == 'true' }}
    outputs:
      cz_version: ${{ steps.cz.outputs.version }}
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: "${{ secrets.GITHUB_TOKEN }}"
      - id: cz
        name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          working_directory: .
          changelog_increment_filename: body.md
      - name: Seriously Print New version
        run: echo "Backend version Uplifted! ${{ steps.cz.outputs.version }}"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: "./body.md"
          tag_name: "v${{ steps.cz.outputs.version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker:
    # Build and push image on docker registry. Executed only if source files have changed
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs:
      - bump_version
      - check_source_file_change
    if: "${{ needs.check_source_file_change.outputs.file_changes == 'true' }}"
    strategy:
      fail-fast: false
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.AZURE_REGISTRY_LOGIN_SERVER }}/${{ env.DOCKER_IMAGE }}
          tags: |
            type=semver,pattern={{version}},value=${{ needs.bump_version.outputs.cz_version }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        if: github.event_name != 'pull_request'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ vars.AZURE_REGISTRY_LOGIN_SERVER }}
          username: ${{ vars.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.SOURCE_PATH }}
          file: ${{ env.DOCKERFILE }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
